[[repos]]
repo = "builtin"
hooks = [
    { id = "check-json" },
    { id = "check-yaml" },
    { id = "check-toml" },
    { id = "end-of-file-fixer" },
]

[[repos]]
repo = "local"
hooks = [
    { id = "cargo-clippy", name = "cargo clippy", entry = "cargo clippy -- -D warnings", language = "system", pass_filenames = false, always_run = true },
    { id = "cargo-fmt", name = "cargo fmt", entry = "cargo fmt", language = "system", pass_filenames = false, always_run = true },
]
